name: 'Execute features'
description: 'Execute features and re execute'

# Inputs the action accepts.
inputs:
  scenarioTag:
    description: 'Scenario Tag to execute(e.g. "@TC-00001")'
    required: false
    default: '@Regression'
  baseUrl:
    description: 'Base Url(e.g. "https://trello.com")'
    required: true
    default: 'https://trello.com'
  userEmail:
    description: 'User email (Web)(e.g. "user@gmail.com")'
    required: false
    default: 'user@gmail.com'
  userPassword:
    description: 'User password (Web)(e.g. "password")'
    required: false
    default: 'password'
  apiUrl:
    description: 'Api Url(e.g. "https://api.trello.com/1")'
    required: false
    default: 'https://api.trello.com/1'
  apiKey:
    description: 'API Key(e.g. "c60889ea05a8592e")'
    required: true
  apiToken:
    description: 'API Token(e.g. "9rc055cf5a711d2")'
    required: true

runs:
  using: "composite"

  steps:
    # Cloning you repository to the runner.
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8 for x64
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
        architecture: x64

    # Using shell script to install Google Chrome.
    - name: Install Google Chrome
      # Install if the user email value is different from the default value.
      if: ${{ inputs.userEmail != 'user@gmail.com' }}
      run: |
        chmod +x ./scripts/InstallChrome.sh
        ./scripts/InstallChrome.sh
      shell: bash

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.9

    - name: Execute Features
      id: execute-features
      run: |
        gradle executeFeatures \
            -Dcucumber.filter.tags="${{ inputs.scenarioTag }}" \
            -Pbrowser="CHROME_HEADLESS" \
            -PbaseUrl="${{ inputs.baseUrl }}" \
            -Puser="${{ inputs.userEmail }}" -Ppassword="${{ inputs.userPassword }}" \
            -PapiUrl="${{ inputs.apiUrl }}" \
            -PapiKey="${{ inputs.apiKey }}" -PapiToken="${{ inputs.apiToken }}"
      shell: bash

    # Re-execute if there are failed scenarios using the 'rerun.txt' file.
    - name: Re-Execute Features
      if: ${{ failure() && steps.execute-features.conclusion == 'failure' }}
      run: |
        gradle reExecuteFeatures \
            -Pbrowser="CHROME_HEADLESS" \
            -PbaseUrl="${{ inputs.baseUrl }}" \
            -Puser="${{ inputs.userEmail }}" -Ppassword="${{ inputs.userPassword }}" \
            -PapiUrl="${{ inputs.apiUrl }}" \
            -PapiKey="${{ inputs.apiKey }}" -PapiToken="${{ inputs.apiToken }}"
      shell: bash

    # Upload log file.
    - name: Upload log file
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: logs${{ github.run_id }}
        path: ./logs
        retention-days: 5
