name: CI

# Controls when the workflow will run.
on:
  # When creating a new pull request to the 'develop' branch.
  pull_request:
    branches: [ develop ]
    paths-ignore: [ '**.md' ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
    inputs:
      scenarioTag:
        description: 'Scenario Tag to execute(e.g. "@TC-00001")'
        type: string
        required: false
        default: '@Regression'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:

  execution:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    steps:
      - id: get-id
        run: echo "branch_ref=$(echo ${{ github.head_ref }} | cut -f2 -d"/")" >> $GITHUB_OUTPUT
      - run: |
          if [[ ${{ steps.get-id.outputs.branch_ref }} =~ "TC" ]]; then
              echo "id_tag1=${{ steps.get-id.outputs.branch_ref }}" >> $GITHUB_OUTPUT
          else
              echo "id_tag2=Empty" >> $GITHUB_OUTPUT
          fi
      - run: |
          echo "${{ steps.get-id.outputs.id_tag1 }}"
          echo "${{ steps.get-id.outputs.id_tag2 }}"

#      - name: test
#        id: checksecrets
#        run: |
#          if [ "TC" == "TC" ]; then
#            echo "secretspresent=NO" >> $GITHUB_OUTPUT
#          else
#            echo "secretspresent=YES" >> $GITHUB_OUTPUT
#          fi
#      - run: echo "${{ steps.checksecrets.outputs.secretspresent }}"

      - name: test2
        id: check
        run: |
          echo "branch_ref=$(echo ${{ github.head_ref }} | cut -f2 -d"/")" >> $GITHUB_OUTPUT
          if [ ${{ steps.get-id.outputs.branch_ref }} = "TC"* ]; then
            echo "secrets=${{ steps.get-id.outputs.branch_ref }}" >> $GITHUB_OUTPUT
          else
            echo "secrets=Empty" >> $GITHUB_OUTPUT
          fi
      - run: echo "${{ steps.check.outputs.secrets }}"

      - name: test3
        id: check1
        run: |
          echo "branch_ref=$(echo ${{ github.head_ref }} | cut -f2 -d"/")" >> $GITHUB_OUTPUT
          if [ "${{ steps.get-id.outputs.branch_ref }}" = Im* ]; then
            echo "secrets=${{ steps.get-id.outputs.branch_ref }}" >> $GITHUB_OUTPUT
          else
            echo "secrets=Empty" >> $GITHUB_OUTPUT
          fi
      - run: echo "${{ steps.check1.outputs.secrets }}"

      - name: test4
        id: check2
        run: |
              input="Bus"
              if [[ $input = Bu* ]]
              then
              echo "Start with B"
              else
              echo "No match"
              fi
              echo $input

      - name: test4
        id: check3
        run: |
          echo "branch_ref=$(echo ${{ github.head_ref }} | cut -f2 -d"/")" >> $GITHUB_OUTPUT
          if [ ${{ steps.get-id.outputs.branch_ref }} = Im* ]; then
            echo "secrets=${{ steps.get-id.outputs.branch_ref }}" >> $GITHUB_OUTPUT
          else
            echo "secrets=Empty" >> $GITHUB_OUTPUT
          fi
      - run: echo "${{ steps.check3.outputs.secrets }}"

      - name: test5
        id: check20
        run: |
          input= ${{ github.head_ref }} | cut -f2 -d"/"
          if [[ $input = Im* ]]
          then
          echo "Start with B"
          else
          echo "No match"
          fi
          echo $input